<%@ Page Title="" Language="C#" MasterPageFile="~/PagesAdmin/NestedAdmin.Master" AutoEventWireup="true" CodeBehind="AdminProduct.aspx.cs" Inherits="ShoppingCart.AdminProduct" %>
<asp:Content ID="Content2" ContentPlaceHolderID="adminContentPlaceHolder" runat="server">
    <h1>Manage Products</h1>
    <asp:GridView ID="gvProducts" runat="server" DataKeyNames="PRODUCT_ID" AutoGenerateColumns="False" DataSourceID="SqlDataSource1" AutoGenerateEditButton="True" AutoGenerateDeleteButton="True" AllowSorting="True">
        <Columns>
            <asp:BoundField DataField="PRODUCT_ID" HeaderText="PRODUCT_ID" ReadOnly="True" SortExpression="PRODUCT_ID" />
            <asp:BoundField DataField="CATEGORY_ID" HeaderText="CATEGORY_ID" SortExpression="CATEGORY_ID" />
            <asp:BoundField DataField="SUBCATEGORY_ID" HeaderText="SUBCATEGORY_ID" SortExpression="SUBCATEGORY_ID" />
            <asp:BoundField DataField="PRODUCT_NAME" HeaderText="PRODUCT_NAME" SortExpression="PRODUCT_NAME" />
            <asp:BoundField DataField="MANUFACTURER" HeaderText="MANUFACTURER" SortExpression="MANUFACTURER" />
            <asp:BoundField DataField="DESC_SHORT" HeaderText="DESC_SHORT" SortExpression="DESC_SHORT" />
            <asp:BoundField DataField="DESC_LONG" HeaderText="DESC_LONG" SortExpression="DESC_LONG" />
            <asp:BoundField DataField="UNIT_WEIGHT" HeaderText="UNIT_WEIGHT" SortExpression="UNIT_WEIGHT" />
            <asp:BoundField DataField="IMAGELOCLRG" HeaderText="IMAGELOCLRG" SortExpression="IMAGELOCLRG" />
            <asp:BoundField DataField="IMAGELOCSML" HeaderText="IMAGELOCSML" SortExpression="IMAGELOCSML" />
            <asp:BoundField DataField="KEYWORDS" HeaderText="KEYWORDS" SortExpression="KEYWORDS" />
            <asp:BoundField DataField="QUANTITY" HeaderText="QUANTITY" SortExpression="QUANTITY" />
            <asp:BoundField DataField="UNIT_PRICE" HeaderText="UNIT_PRICE" SortExpression="UNIT_PRICE" />
        </Columns>
    </asp:GridView>
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="Data Source=&quot;128.172.188.42, 14330&quot;;Initial Catalog=fall16_g3;Persist Security Info=True;User ID=fall16_g3;Password=Fallgrp3!" ProviderName="System.Data.SqlClient" SelectCommand="SELECT [PRODUCT_ID], [CATEGORY_ID], [SUBCATEGORY_ID], [PRODUCT_NAME], [MANUFACTURER], [DESC_SHORT], [DESC_LONG], [UNIT_WEIGHT], [IMAGELOCLRG], [IMAGELOCSML], [KEYWORDS], [QUANTITY], [UNIT_PRICE] FROM [PRODUCT]"></asp:SqlDataSource>
    <asp:ObjectDataSource ID="odsProducts" runat="server" SelectMethod="getProductList" TypeName="ShoppingCart.BusinessLogic" DataObjectTypeName="ShoppingCart.Product" UpdateMethod="updateProduct"></asp:ObjectDataSource>
</asp:Content>
