<%@ Page Title="" Language="C#" MasterPageFile="~/PagesAdmin/NestedAdmin.Master" AutoEventWireup="true" CodeBehind="AdminCategories.aspx.cs" Inherits="ShoppingCart.AdminCategories" %>
<asp:Content ID="Content2" ContentPlaceHolderID="adminContentPlaceHolder" runat="server">
    <h1>Manage Categories</h1>
    <asp:GridView ID="gvProducts" runat="server" DataKeyNames="CATEGORY_ID" AutoGenerateColumns="False" DataSourceID="SqlDataSource1" AutoGenerateEditButton="True" AutoGenerateDeleteButton="True" AllowSorting="True" AllowPaging="True">
        <Columns>
            <asp:BoundField DataField="CATEGORY_ID" HeaderText="CATEGORY_ID" ReadOnly="True" SortExpression="CATEGORY_ID" />
            <asp:BoundField DataField="CATEGORY_NAME" HeaderText="CATEGORY_NAME" SortExpression="CATEGORY_NAME" />
            <asp:BoundField DataField="CATEGORY_DESCRIPTION" HeaderText="CATEGORY_DESCRIPTION" SortExpression="CATEGORY_DESCRIPTION" />
        </Columns>
    </asp:GridView>
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:fall16_g3ConnectionString %>" SelectCommand="SELECT [CATEGORY_ID], [CATEGORY_NAME], [CATEGORY_DESCRIPTION] FROM [CATEGORY]"></asp:SqlDataSource>
    <asp:ObjectDataSource ID="odsProducts" runat="server" SelectMethod="getProductList" TypeName="ShoppingCart.BusinessLogic" DataObjectTypeName="ShoppingCart.Product" UpdateMethod="updateProduct"></asp:ObjectDataSource>
</asp:Content>
