<%@ Page Title="" Language="C#" MasterPageFile="~/PagesAdmin/NestedAdmin.Master" AutoEventWireup="true" CodeBehind="AdminOrders.aspx.cs" Inherits="ShoppingCart.AdminOrders" %>
<asp:Content ID="Content2" ContentPlaceHolderID="adminContentPlaceHolder" runat="server">
    <h1>Manage Products</h1>
    <asp:GridView ID="gvProducts" runat="server" DataKeyNames="ORDER_ID" AutoGenerateColumns="False" DataSourceID="SqlDataSource1" AutoGenerateEditButton="True" AutoGenerateDeleteButton="True" AllowSorting="True" AllowPaging="True">
        <Columns>
            <asp:BoundField DataField="ORDER_ID" HeaderText="ORDER_ID" ReadOnly="True" SortExpression="ORDER_ID" />
            <asp:BoundField DataField="CUSTOMER_ID" HeaderText="CUSTOMER_ID" SortExpression="CUSTOMER_ID" />
            <asp:BoundField DataField="PRODUCT_ID" HeaderText="PRODUCT_ID" SortExpression="PRODUCT_ID" />
            <asp:BoundField DataField="ORDER_QUANTITY" HeaderText="ORDER_QUANTITY" SortExpression="ORDER_QUANTITY" />
            <asp:BoundField DataField="ORDER_PRODUCT_COST" HeaderText="ORDER_PRODUCT_COST" SortExpression="ORDER_PRODUCT_COST" />
            <asp:BoundField DataField="ORDER_STATUS" HeaderText="ORDER_STATUS" SortExpression="ORDER_STATUS" />
            <asp:BoundField DataField="SALE_DATE" HeaderText="SALE_DATE" SortExpression="SALE_DATE" />
        </Columns>
    </asp:GridView>
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:fall16_g3ConnectionString %>" SelectCommand="SELECT [ORDER_ID], [CUSTOMER_ID], [PRODUCT_ID], [ORDER_QUANTITY], [ORDER_PRODUCT_COST], [ORDER_STATUS], [SALE_DATE] FROM [ORDER_DETAILS] ORDER BY [SALE_DATE]" DeleteCommand="DELETE FROM [ORDER_DETAILS] WHERE [ORDER_ID] = @ORDER_ID" InsertCommand="INSERT INTO [ORDER_DETAILS] ([ORDER_ID], [CUSTOMER_ID], [PRODUCT_ID], [ORDER_QUANTITY], [ORDER_PRODUCT_COST], [ORDER_STATUS], [SALE_DATE]) VALUES (@ORDER_ID, @CUSTOMER_ID, @PRODUCT_ID, @ORDER_QUANTITY, @ORDER_PRODUCT_COST, @ORDER_STATUS, @SALE_DATE)" UpdateCommand="UPDATE [ORDER_DETAILS] SET [CUSTOMER_ID] = @CUSTOMER_ID, [PRODUCT_ID] = @PRODUCT_ID, [ORDER_QUANTITY] = @ORDER_QUANTITY, [ORDER_PRODUCT_COST] = @ORDER_PRODUCT_COST, [ORDER_STATUS] = @ORDER_STATUS, [SALE_DATE] = @SALE_DATE WHERE [ORDER_ID] = @ORDER_ID">
        <DeleteParameters>
            <asp:Parameter Name="ORDER_ID" Type="Int32" />
        </DeleteParameters>
        <InsertParameters>
            <asp:Parameter Name="ORDER_ID" Type="Int32" />
            <asp:Parameter Name="CUSTOMER_ID" Type="Int32" />
            <asp:Parameter Name="PRODUCT_ID" Type="Int32" />
            <asp:Parameter Name="ORDER_QUANTITY" Type="Int32" />
            <asp:Parameter Name="ORDER_PRODUCT_COST" Type="Decimal" />
            <asp:Parameter Name="ORDER_STATUS" Type="String" />
            <asp:Parameter DbType="Date" Name="SALE_DATE" />
        </InsertParameters>
        <UpdateParameters>
            <asp:Parameter Name="CUSTOMER_ID" Type="Int32" />
            <asp:Parameter Name="PRODUCT_ID" Type="Int32" />
            <asp:Parameter Name="ORDER_QUANTITY" Type="Int32" />
            <asp:Parameter Name="ORDER_PRODUCT_COST" Type="Decimal" />
            <asp:Parameter Name="ORDER_STATUS" Type="String" />
            <asp:Parameter DbType="Date" Name="SALE_DATE" />
            <asp:Parameter Name="ORDER_ID" Type="Int32" />
        </UpdateParameters>
    </asp:SqlDataSource>
    <asp:ObjectDataSource ID="odsProducts" runat="server" SelectMethod="getProductList" TypeName="ShoppingCart.BusinessLogic" DataObjectTypeName="ShoppingCart.Product" UpdateMethod="updateProduct"></asp:ObjectDataSource>
</asp:Content>
