<%@ Page Title="" Language="C#" MasterPageFile="~/PagesAdmin/NestedAdmin.Master" AutoEventWireup="true" CodeBehind="AdminUsers.aspx.cs" Inherits="ShoppingCart.AdminUsers" %>
<asp:Content ID="Content2" ContentPlaceHolderID="adminContentPlaceHolder" runat="server">
    <h1>Manage Users</h1>
    <asp:GridView ID="gvProducts" runat="server" DataKeyNames="CUSTOMER_ID" AutoGenerateColumns="False" DataSourceID="SqlDataSource1" AutoGenerateEditButton="True" AutoGenerateDeleteButton="True" AllowSorting="True" AllowPaging="True">
        <Columns>
            <asp:BoundField DataField="CUSTOMER_ID" HeaderText="CUSTOMER_ID" ReadOnly="True" SortExpression="CUSTOMER_ID" />
            <asp:BoundField DataField="FIRST_NAME" HeaderText="FIRST_NAME" SortExpression="FIRST_NAME" />
            <asp:BoundField DataField="SHIPPING_ADDRESS" HeaderText="SHIPPING_ADDRESS" SortExpression="SHIPPING_ADDRESS" />
            <asp:BoundField DataField="LAST_NAME" HeaderText="LAST_NAME" SortExpression="LAST_NAME" />
            <asp:BoundField DataField="BILLING_ADDRESS" HeaderText="BILLING_ADDRESS" SortExpression="BILLING_ADDRESS" />
            <asp:BoundField DataField="PHONE" HeaderText="PHONE" SortExpression="PHONE" />
            <asp:BoundField DataField="EMAIL" HeaderText="EMAIL" SortExpression="EMAIL" />
            <asp:BoundField DataField="USERNAME" HeaderText="USERNAME" SortExpression="USERNAME" />
            <asp:BoundField DataField="STATUS_FLAG" HeaderText="STATUS_FLAG" SortExpression="STATUS_FLAG" />
            <asp:BoundField DataField="CREDIT_APPROVAL" HeaderText="CREDIT_APPROVAL" SortExpression="CREDIT_APPROVAL" />
            <asp:BoundField DataField="WEBSITE" HeaderText="WEBSITE" SortExpression="WEBSITE" />
            <asp:BoundField DataField="PASSWORD" HeaderText="PASSWORD" SortExpression="PASSWORD" />
        </Columns>
    </asp:GridView>
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:fall16_g3ConnectionString %>" SelectCommand="SELECT [CUSTOMER_ID], [FIRST_NAME], [SHIPPING_ADDRESS], [LAST_NAME], [BILLING_ADDRESS], [PHONE], [EMAIL], [USERNAME], [STATUS_FLAG], [CREDIT_APPROVAL], [WEBSITE], [PASSWORD] FROM [CUSTOMER]" DeleteCommand="DELETE FROM [CUSTOMER] WHERE [CUSTOMER_ID] = @CUSTOMER_ID" InsertCommand="INSERT INTO [CUSTOMER] ([CUSTOMER_ID], [FIRST_NAME], [SHIPPING_ADDRESS], [LAST_NAME], [BILLING_ADDRESS], [PHONE], [EMAIL], [USERNAME], [STATUS_FLAG], [CREDIT_APPROVAL], [WEBSITE], [PASSWORD]) VALUES (@CUSTOMER_ID, @FIRST_NAME, @SHIPPING_ADDRESS, @LAST_NAME, @BILLING_ADDRESS, @PHONE, @EMAIL, @USERNAME, @STATUS_FLAG, @CREDIT_APPROVAL, @WEBSITE, @PASSWORD)" UpdateCommand="UPDATE [CUSTOMER] SET [FIRST_NAME] = @FIRST_NAME, [SHIPPING_ADDRESS] = @SHIPPING_ADDRESS, [LAST_NAME] = @LAST_NAME, [BILLING_ADDRESS] = @BILLING_ADDRESS, [PHONE] = @PHONE, [EMAIL] = @EMAIL, [USERNAME] = @USERNAME, [STATUS_FLAG] = @STATUS_FLAG, [CREDIT_APPROVAL] = @CREDIT_APPROVAL, [WEBSITE] = @WEBSITE, [PASSWORD] = @PASSWORD WHERE [CUSTOMER_ID] = @CUSTOMER_ID">
        <DeleteParameters>
            <asp:Parameter Name="CUSTOMER_ID" Type="Int32" />
        </DeleteParameters>
        <InsertParameters>
            <asp:Parameter Name="CUSTOMER_ID" Type="Int32" />
            <asp:Parameter Name="FIRST_NAME" Type="String" />
            <asp:Parameter Name="SHIPPING_ADDRESS" Type="String" />
            <asp:Parameter Name="LAST_NAME" Type="String" />
            <asp:Parameter Name="BILLING_ADDRESS" Type="String" />
            <asp:Parameter Name="PHONE" Type="String" />
            <asp:Parameter Name="EMAIL" Type="String" />
            <asp:Parameter Name="USERNAME" Type="String" />
            <asp:Parameter Name="STATUS_FLAG" Type="String" />
            <asp:Parameter Name="CREDIT_APPROVAL" Type="String" />
            <asp:Parameter Name="WEBSITE" Type="String" />
            <asp:Parameter Name="PASSWORD" Type="String" />
        </InsertParameters>
        <UpdateParameters>
            <asp:Parameter Name="FIRST_NAME" Type="String" />
            <asp:Parameter Name="SHIPPING_ADDRESS" Type="String" />
            <asp:Parameter Name="LAST_NAME" Type="String" />
            <asp:Parameter Name="BILLING_ADDRESS" Type="String" />
            <asp:Parameter Name="PHONE" Type="String" />
            <asp:Parameter Name="EMAIL" Type="String" />
            <asp:Parameter Name="USERNAME" Type="String" />
            <asp:Parameter Name="STATUS_FLAG" Type="String" />
            <asp:Parameter Name="CREDIT_APPROVAL" Type="String" />
            <asp:Parameter Name="WEBSITE" Type="String" />
            <asp:Parameter Name="PASSWORD" Type="String" />
            <asp:Parameter Name="CUSTOMER_ID" Type="Int32" />
        </UpdateParameters>
    </asp:SqlDataSource>
    <asp:ObjectDataSource ID="odsProducts" runat="server" SelectMethod="getProductList" TypeName="ShoppingCart.BusinessLogic" DataObjectTypeName="ShoppingCart.Product" UpdateMethod="updateProduct"></asp:ObjectDataSource>
</asp:Content>
